version: '3.8'

services:
  tic-tac-toe-prod:
    build:
      context: .
      target: production # This specifies that Docker should use the 'development' stage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

